title: Portefølje
description: Portefølje 4. Semester
baseurl: "" 
url: "https://lika62310.github.io"
theme: minima

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

plugins:
  - jekyll-feed
